  {
    id: 16,
    slug: 'stack-top-tiles',
    title: 'Медиа сверху · сетка превью',
    summary: 'Сверху сетка средних 16:9 на всю ширину, под ней текст ≤50%.',
    layout: 'composition-stack-top',
    composition: 'tiles',
    textShare: 0.5,
    textLength: 'long',
    compact: false,
    mediaCount: 6,
    includeVideo: true,
    series: 'stack',
  },