  {
    id: 17,
    slug: 'stack-top-rail',
    title: 'Медиа сверху · горизонтальная лента',
    summary: 'Сверху лента средних карточек на всю ширину, текст ≤50% ниже.',
    layout: 'composition-stack-top',
    composition: 'rail',
    textShare: 0.5,
    textLength: 'long',
    compact: false,
    mediaCount: 6,
    includeVideo: true,
    series: 'stack',
  },