  {
    id: 19,
    slug: 'stack-bottom-bento',
    title: 'Медиа снизу · bento',
    summary: 'Сначала текст ≤50%, под ним bento-мозаика на всю ширину.',
    layout: 'composition-stack-bottom',
    composition: 'bento',
    textShare: 0.5,
    textLength: 'long',
    compact: false,
    mediaCount: 5,
    includeVideo: true,
    series: 'stack',
  },