  {
    id: 23,
    slug: 'stack-top-single',
    title: 'Медиа сверху · одно фото',
    summary: 'Как вариант 17, но одно изображение на всю ширину без слайдера. Текст ≤50% ниже.',
    layout: 'composition-stack-top',
    composition: 'rail',
    textShare: 0.5,
    textLength: 'long',
    compact: false,
    mediaCount: 1,
    includeVideo: false,
    series: 'stack',
  },