  {
    id: 25,
    slug: 'stack-top-triple',
    title: 'Медиа сверху · 3 карточки',
    summary: 'Как вариант 24: 3 карточки в ряд, слайдер со стрелками на кадрах. Текст ≤50% ниже.',
    layout: 'composition-stack-top',
    composition: 'triple',
    textShare: 0.5,
    textLength: 'long',
    compact: false,
    mediaCount: 6,
    includeVideo: true,
    series: 'stack',
  },