  {
    id: 27,
    slug: 'stack-top-one',
    title: 'Медиа сверху · 1 карточка',
    summary: 'Как вариант 25, но одна карточка того же размера, без слайдера.',
    layout: 'composition-stack-top',
    composition: 'triple',
    textShare: 0.5,
    textLength: 'long',
    compact: false,
    mediaCount: 1,
    includeVideo: false,
    series: 'stack',
  },