  {
    id: 28,
    slug: 'stack-top-duo',
    title: 'Медиа сверху · 2 карточки',
    summary: 'Как вариант 25, но две карточки того же размера, без слайдера.',
    layout: 'composition-stack-top',
    composition: 'triple',
    textShare: 0.5,
    textLength: 'long',
    compact: false,
    mediaCount: 2,
    includeVideo: true,
    series: 'stack',
  },